apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flagd
  name: flagd
  namespace: flagd-performance-test
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8013
  selector:
    app: flagd
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flagd-http
  name: flagd-http
  namespace: flagd-performance-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: flagd-http