apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flagd
  name: flagd
  namespace: flagd-performance-test
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: flagd